runtime: nodejs10
service: default
env_variables:
  SQL_USER: 'root'
  SQL_PASSWORD: '123456'
  SQL_DATABASE: 'parkingDatabase'
  INSTANCE_CONNECTION_NAME: 'parking-spot-260815:us-central1:parking-data-12345'
  NODE_ENV: 'production'
beta_settings:
    # The connection name of your instance, available by using
    # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
    # the Instance details page in the Google Cloud Platform Console.
        cloud_sql_instances: 'parking-spot-260815:us-central1:parking-data-12345'
